# Generated by Django 4.2.7 on 2023-12-22 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500, null=True)),
                ('order_total', models.FloatField()),
                ('products', models.JSONField()),
                ('status', models.CharField(choices=[('shipped', 'shipped'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('delivered', 'delivered')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
